catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

packages: []

catalogs:
  build:
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint': ^1.12.1
    '@nuxt/kit': ^4.2.0
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.3
    '@unocss/eslint-config': ^66.5.10
    '@unocss/nuxt': ^66.5.10
    '@vueuse/nuxt': ^14.1.0
    nuxt: ^4.2.2
    unocss: ^66.5.10
    unplugin: ^2.3.10
    vite: ^7.1.12
  deploy:
    '@netlify/nuxt': ^0.2.15
  dev:
    '@antfu/eslint-config': ^6.6.1
    eslint: ^9.39.1
    eslint-plugin-format: ^1.1.0
    typescript: ^5.9.3
    vue-tsc: ^3.1.8
  frontend:
    '@vueuse/core': ^14.1.0
    pinia: ^3.0.4
    vue: ^3.5.25
  icons:
    '@iconify-json/carbon': ^1.2.15
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/twemoji': ^1.2.4
    '@unocss/preset-icons': ^66.5.10
  sdk:
    '@atproto/api': ^0.18.7

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
